export enum ErrorCodes {
	INVALID_URL = 'ERR_INVALID_URL',
	SERVICE_MISMATCH = 'ERR_SERVICE_MISMATCH',
	INVALID_RANGE = 'ERR_INVALID_RANGE',
	EXTRACTION_FAILED = 'ERR_EXTRACTION_FAILED',
	DOWNLOAD_FAILED = 'ERR_DOWNLOAD_FAILED',
	UNKNOWN_ERROR = 'ERR_UNKNOWN_ERROR',
	UNSUPPORTED_METHOD = 'ERR_UNSUPPORTED_METHOD',
	REQUIRED_FIELD_MISSING = 'ERR_REQUIRED_FIELD_MISSING',
	INVALID_SERVICE = 'ERR_INVALID_SERVICE',
	GENERIC_ERROR = 'ERR_GENERIC_ERROR',
	ENOENT = 'ENOENT_NO_SUCH_FILE_OR_DIRECTORY',
	HTTP_404 = 'HTTP_404',
	URL_INVALID = 'URL_INVALID',
	HLS_TOKEN_EXPIRED = 'HLS_TOKEN_EXPIRED',
	NOT_IMPLEMENTED = 'ERR_NOT_IMPLEMENTED',
	UNSUPPORTED_OPERATION = 'ERR_UNSUPPORTED_OPERATION'
}
