export type ExecutionShape = 'single' | 'multiple';

export type InferExecutionShape<T> = T extends any[] ? 'multiple' : 'single';

export type ShapeOutput<T, S extends ExecutionShape> = S extends 'multiple' ? T[] : T;

/** Job execution strategy */
export enum ExecutionType {
	/** Sequential task execution */
	SEQUENTIAL = 'SEQUENTIAL',

	/** Concurrent task execution */
	PARALLEL = 'PARALLEL'
}

/** URL category for extraction and pipeline routing */
export enum ExtractionTarget {
	/** Anchor href URLs */
	ANCHORS = 'ANCHORS',

	/** Image URLs */
	IMAGES = 'IMAGES',

	/** Div href URLs */
	DIV_HREFS = 'DIV_HREFS',

	/** Media source URLs */
	SOURCES = 'SOURCES',

	/** Video poster URLs */
	VIDEO_POSTER = 'VIDEO_POSTER',

	/** All discovered URLs */
	ALL_URLS = 'ALL_URLS'
}

export enum Provider {
	// <auto-generated:entries>
	AnalRz = 'AnalRzProvider',
	ArtStation = 'ArtStationProvider',
	Beeg = 'BeegProvider',
	Behance = 'BehanceProvider',
	BlackPorn = 'BlackPornProvider',
	Bluesky = 'BlueskyProvider',
	BoKepPorn = 'BoKepPornProvider',
	ColliderPorn = 'ColliderPornProvider',
	CumLouder = 'CumLouderProvider',
	DaFreePorn = 'DaFreePornProvider',
	Danbooru = 'DanbooruProvider',
	DaNude = 'DaNudeProvider',
	Default = 'DefaultProvider',
	DeviantArt = 'DeviantArtProvider',
	EpicGfs = 'EpicGfsProvider',
	EPorner = 'EPornerProvider',
	Flickr = 'FlickrProvider',
	Gelbooru = 'GelbooruProvider',
	HqPorn = 'HqPornProvider',
	Imgur = 'ImgurProvider',
	Instagram = 'InstagramProvider',
	Interracial = 'InterracialProvider',
	ItsPorn = 'ItsPornProvider',
	Lesbian8 = 'Lesbian8Provider',
	MangaDex = 'MangaDexProvider',
	Mastodon = 'MastodonProvider',
	MegaTube = 'MegaTubeProvider',
	MomVids = 'MomVidsProvider',
	MyLust = 'MyLustProvider',
	Newgrounds = 'NewgroundsProvider',
	OkPorn = 'OkPornProvider',
	PerfectGirls = 'PerfectGirlsProvider',
	Pexels = 'PexelsProvider',
	Pinterest = 'PinterestProvider',
	Pixiv = 'PixivProvider',
	Porn300 = 'Porn300Provider',
	PornDoe = 'PornDoeProvider',
	PornHub = 'PornHubProvider',
	PornId = 'PornIdProvider',
	PornOne = 'PornOneProvider',
	PornSeven = 'PornSevenProvider',
	PornsOk = 'PornsOkProvider',
	PussySpace = 'PussySpaceProvider',
	Reddit = 'RedditProvider',
	SexVid = 'SexVidProvider',
	Shameless = 'ShamelessProvider',
	SuperPorn = 'SuperPornProvider',
	SxyPorn = 'SxyPornProvider',
	TheyAreHuge = 'TheyAreHugeProvider',
	TikTok = 'TikTokProvider',
	TnAFlix = 'TnAFlixProvider',
	TubeVSex = 'TubeVSexProvider',
	Tumblr = 'TumblrProvider',
	Twitter = 'TwitterProvider',
	Unsplash = 'UnsplashProvider',
	WallHaven = 'WallHavenProvider',
	WikiArt = 'WikiArtProvider',
	Wikimedia = 'WikimediaProvider',
	XCafe = 'XCafeProvider',
	XDegu = 'XDeguProvider',
	XGroovy = 'XGroovyProvider',
	XHamster = 'XHamsterProvider',
	XnXX = 'XnXXProvider',
	Xozilla = 'XozillaProvider',
	XVideos = 'XVideosProvider',
	ZbPorn = 'ZbPornProvider',
	ZzzTube = 'ZzzTubeProvider'
	// </auto-generated:entries>
}

export const providerPatterns: Record<Provider, RegExp> = {
	[Provider.Pixiv]: /^(?:www\.)?pixiv\.net$/i,
	[Provider.XHamster]: /^(?:xhamster|xhopen|xhtotal)(?:\d+)?(?:\.com|\.desi)$/i,
	[Provider.XnXX]: /^(?:www\.)?xnxx(?:\d+)?\.(?:com|health)$/i,
	[Provider.Twitter]: /^(?:www\.)?(?:twitter|x)\.com$/i,
	[Provider.PussySpace]: /^(?:www\.)?pussyspace\.(?:com)$/i,
	[Provider.PornDoe]: /^(?:(?:www|de|en|fs|pt|es|fr|it)\.)?porndoe\.(?:com)$/i,
	[Provider.MyLust]: /^(?:(?:www|de|ru)\.)?mylust\.(?:com)$/i,
	[Provider.HqPorn]: /^(?:www\.)?hqporn\.(?:com|xxx)$/i,
	[Provider.EpicGfs]: /(?:www\.)?epicgfs\.(?:com)$/i,
	[Provider.Interracial]: /(?:www\.)?interracial\.(?:com)$/i,
	[Provider.BoKepPorn]: /(?:www\.)?bokep\.(?:porn)$/i,
	[Provider.CumLouder]: /^(?:www\.)?cumlouder\.(?:com)$/i,
	[Provider.PornOne]: /^(?:www\.)?pornone\.(?:com|net)$/i,
	[Provider.PornSeven]: /^(?:www\.)?porn7\.(?:xxx)$/i,
	[Provider.DeviantArt]: /^(?:www\.)?deviantart\.com$/i,
	[Provider.XVideos]: /(?:www\.)?xvideos(?:\d+)?\.(?:com)$/i,
	[Provider.Pinterest]: /^(?:www\.)?pinterest\.[a-z.]+$/i,
	[Provider.SexVid]: /^(?:www\.)?sexvid(?:\d+)?\.(?:xxx|com)$/i,
	[Provider.ArtStation]: /^(?:www\.)?artstation\.com$/i,
	[Provider.Mastodon]: /^(?:mastodon\.social|mastodon\.online|mstdn\.social|fosstodon\.org|techhub\.social)$/i,
	[Provider.TheyAreHuge]: /^(?:www\.)?theyarehuge\.(?:com)$/i,
	[Provider.Beeg]: /^(?:www\.)?beeg\.(?:com)$/i,
	[Provider.Danbooru]: /^(?:www\.)?danbooru\.donmai\.us$/i,
	[Provider.Pexels]: /^(?:www\.)?pexels\.com$/i,
	[Provider.PerfectGirls]: /^(?:www\.)?(?:perfectgirls|perfectdamen)\.(?:co|xxx)$/i,
	[Provider.Imgur]: /^(?:i\.)?imgur\.com$/i,
	[Provider.Flickr]: /^(?:www\.)?flickr\.com$/i,
	[Provider.MegaTube]: /^(?:www\.)?megatube\.(?:xxx)$/i,
	[Provider.MangaDex]: /^(?:www\.)?mangadex\.org$/i,
	[Provider.PornHub]: /^(?:www\.)?pornhub\.(?:com|net|org)$/i,
	[Provider.Lesbian8]: /(?:www\.)?lesbian8\.(?:com|net)$/i,
	[Provider.Gelbooru]: /^(?:www\.)?gelbooru\.com$/i,
	[Provider.Default]: /\.*/i,
	[Provider.XGroovy]: /^(?:(?:www|rt|pt|de|es|pl|it|cn|jp|ko|nl)?\.)?xgroovy(?:-fr)?\.(?:com)$/i,
	[Provider.SxyPorn]: /^(?:www\.)?sxyprn\.(?:com)$/i,
	[Provider.XDegu]: /(?:www\.)?xdegu\.(?:com)$/i,
	[Provider.Tumblr]: /^(?:www\.)?tumblr\.com$|^(?:[a-z0-9-]+\.)?tumblr\.com$/i,
	[Provider.PornId]: /(?:www\.)?pornid\.(?:xxx|name)$/i,
	[Provider.ZbPorn]: /(?:www\.)?zbporn\.(?:tv|com)$/i,
	[Provider.Shameless]: /^(?:www\.)?shameless\.(?:com)$/i,
	[Provider.AnalRz]: /^(?:www\.)?analrz\.(?:com)$/i,
	[Provider.DaNude]: /(?:www\.)?danude\.(?:com)$/i,
	[Provider.Bluesky]: /^(?:bsky\.app|(?:[a-z0-9-]+\.)*bsky\.social)$/i,
	[Provider.ColliderPorn]: /^(?:www\.)?colliderporn\.(?:com)$/i,
	[Provider.Reddit]: /^(?:www\.|old\.)?reddit\.com$/i,
	[Provider.Newgrounds]: /^(?:www\.)?newgrounds\.com$/i,
	[Provider.OkPorn]: /^(?:www\.)?ok\.(?:porn|xxx)$/i,
	[Provider.TnAFlix]: /^(?:www\.)?tnaflix\.(?:com)$/i,
	[Provider.Porn300]: /^(?:www\.)?porn300(?:\d+)?\.(?:com|net)$/i,
	[Provider.WallHaven]: /^(?:(?:www|th|w)\.)?wallhaven\.cc$/i,
	[Provider.SuperPorn]: /^(?:www\.)?superporn\.(?:com)$/i,
	[Provider.Behance]: /^(?:www\.)?behance\.net$/i,
	[Provider.WikiArt]: /^(?:www\.)?wikiart\.org$/i,
	[Provider.MomVids]: /(?:www\.)?momvids\.(?:com)$/i,
	[Provider.Unsplash]: /^(?:www\.)?unsplash\.com$/i,
	[Provider.ZzzTube]: /^(?:www\.)?zzztube\.(?:com)$/i,
	[Provider.DaFreePorn]: /(?:www\.)?dafreeporn\.(?:com)$/i,
	[Provider.TikTok]: /^(?:www\.)?tiktok\.com$/i,
	[Provider.EPorner]: /(?:(?:www|pl|en|fr|es|pt|it|de|nl|ph|jp)\.)?eporner\.(?:com)$/i,
	[Provider.Instagram]: /^(?:www\.)?instagram\.com$/i,
	[Provider.PornsOk]: /^(?:www\.)?pornsok\.(?:com)$/i,
	[Provider.TubeVSex]: /^(?:www\.)?tubev\.(?:sex)$/i,
	[Provider.Xozilla]: /(?:www\.)?xozilla\.(?:com|xxx)$/i,
	[Provider.Wikimedia]: /^(?:commons\.)?wikimedia\.org$/i,
	[Provider.ItsPorn]: /(?:www\.)?its\.(?:porn)$/i,
	[Provider.XCafe]: /^(?:www\.)?xcafe\.(?:com)$/i,
	[Provider.BlackPorn]: /^(?:www\.)?blackporn\.(?:tube)$/i
};

export type UrlFormat = 'url' | 'path';

/** Video quality labels */
export enum VideoQuality {
	/** 144p quality */
	Q144 = '144p',

	/** 240p quality */
	Q240 = '240p',

	/** 360p quality */
	Q360 = '360p',

	/** 480p quality */
	Q480 = '480p',

	/** 720p quality */
	Q720 = '720p',

	/** 1080p quality */
	Q1080 = '1080p',

	/** 1440p quality */
	Q1440 = '1440p',

	/** 2160p quality */
	Q2160 = '2160p',

	/** 4320p quality */
	Q4320 = '4320p',
	/** Unknown quality */
	QUnknown = 'unknown'
}

/** Video stream formats */
export enum VideoFormat {
	/** HTTP Live Streaming */
	HLS = 'hls',

	/** MPEG-4 Part 14 */
	MP4 = 'mp4'
}

/** Video codec formats */
export enum VideoCodec {
	/** H.264 / AVC */
	H264 = 'h264',

	/** AV1 (AOMedia Video 1) */
	AV1 = 'av1'
}
