import { BasePipeline } from '@base';
import { type ExecutionArgs, type PipelineItem } from '@contracts';
import { type FileManager } from '@storage';
import { Provider } from '@types';

type PipelineCtor = new (fileManager: FileManager) => BasePipeline<any, any>;

type PipelineFactory = () => Promise<PipelineCtor>;

async function loadPipeline<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Pipeline export "${key}" was not found`);

	return exported as T;
}

const pipelineFactories: Record<Provider, PipelineFactory> = {
	// <auto-generated:entries>
	[Provider.AnalRz]: () => loadPipeline(() => import('@provider/analrz'), 'AnalRzPipeline'),
	[Provider.ArtStation]: () => loadPipeline(() => import('@provider/artstation'), 'ArtStationPipeline'),
	[Provider.Beeg]: () => loadPipeline(() => import('@provider/beeg'), 'BeegPipeline'),
	[Provider.Behance]: () => loadPipeline(() => import('@provider/behance'), 'BehancePipeline'),
	[Provider.BlackPorn]: () => loadPipeline(() => import('@provider/blackporn'), 'BlackPornPipeline'),
	[Provider.Bluesky]: () => loadPipeline(() => import('@provider/bluesky'), 'BlueskyPipeline'),
	[Provider.BoKepPorn]: () => loadPipeline(() => import('@provider/bokepporn'), 'BoKepPornPipeline'),
	[Provider.ColliderPorn]: () => loadPipeline(() => import('@provider/colliderporn'), 'ColliderPornPipeline'),
	[Provider.CumLouder]: () => loadPipeline(() => import('@provider/cumlouder'), 'CumLouderPipeline'),
	[Provider.DaFreePorn]: () => loadPipeline(() => import('@provider/dafreeporn'), 'DaFreePornPipeline'),
	[Provider.Danbooru]: () => loadPipeline(() => import('@provider/danbooru'), 'DanbooruPipeline'),
	[Provider.DaNude]: () => loadPipeline(() => import('@provider/danude'), 'DaNudePipeline'),
	[Provider.Default]: async () => BasePipeline,
	[Provider.DeviantArt]: () => loadPipeline(() => import('@provider/deviantart'), 'DeviantArtPipeline'),
	[Provider.EpicGfs]: () => loadPipeline(() => import('@provider/epicgfs'), 'EpicGfsPipeline'),
	[Provider.EPorner]: () => loadPipeline(() => import('@provider/eporner'), 'EPornerPipeline'),
	[Provider.Flickr]: () => loadPipeline(() => import('@provider/flickr'), 'FlickrPipeline'),
	[Provider.Gelbooru]: async () => BasePipeline,
	[Provider.HqPorn]: () => loadPipeline(() => import('@provider/hqporn'), 'HqPornPipeline'),
	[Provider.Imgur]: () => loadPipeline(() => import('@provider/imgur'), 'ImgurPipeline'),
	[Provider.Instagram]: () => loadPipeline(() => import('@provider/instagram'), 'InstagramPipeline'),
	[Provider.Interracial]: () => loadPipeline(() => import('@provider/interracial'), 'InterracialPipeline'),
	[Provider.ItsPorn]: () => loadPipeline(() => import('@provider/itsporn'), 'ItsPornPipeline'),
	[Provider.Lesbian8]: () => loadPipeline(() => import('@provider/lesbian8'), 'Lesbian8Pipeline'),
	[Provider.MangaDex]: () => loadPipeline(() => import('@provider/mangadex'), 'MangaDexPipeline'),
	[Provider.Mastodon]: () => loadPipeline(() => import('@provider/mastodon'), 'MastodonPipeline'),
	[Provider.MegaTube]: () => loadPipeline(() => import('@provider/megatube'), 'MegaTubePipeline'),
	[Provider.MomVids]: () => loadPipeline(() => import('@provider/momvids'), 'MomVidsPipeline'),
	[Provider.MyLust]: () => loadPipeline(() => import('@provider/mylust'), 'MyLustPipeline'),
	[Provider.Newgrounds]: () => loadPipeline(() => import('@provider/newgrounds'), 'NewgroundsPipeline'),
	[Provider.OkPorn]: () => loadPipeline(() => import('@provider/okporn'), 'OkPornPipeline'),
	[Provider.PerfectGirls]: () => loadPipeline(() => import('@provider/perfectgirls'), 'PerfectGirlsPipeline'),
	[Provider.Pexels]: () => loadPipeline(() => import('@provider/pexels'), 'PexelsPipeline'),
	[Provider.Pinterest]: () => loadPipeline(() => import('@provider/pinterest'), 'PinterestPipeline'),
	[Provider.Pixiv]: () => loadPipeline(() => import('@provider/pixiv'), 'PixivPipeline'),
	[Provider.Porn300]: () => loadPipeline(() => import('@provider/porn300'), 'Porn300Pipeline'),
	[Provider.PornDoe]: () => loadPipeline(() => import('@provider/porndoe'), 'PornDoePipeline'),
	[Provider.PornHub]: () => loadPipeline(() => import('@provider/pornhub'), 'PornHubPipeline'),
	[Provider.PornId]: () => loadPipeline(() => import('@provider/pornid'), 'PornIdPipeline'),
	[Provider.PornOne]: () => loadPipeline(() => import('@provider/pornone'), 'PornOnePipeline'),
	[Provider.PornSeven]: () => loadPipeline(() => import('@provider/pornseven'), 'PornSevenPipeline'),
	[Provider.PornsOk]: () => loadPipeline(() => import('@provider/pornsok'), 'PornsOkPipeline'),
	[Provider.PussySpace]: () => loadPipeline(() => import('@provider/pussyspace'), 'PussySpacePipeline'),
	[Provider.Reddit]: () => loadPipeline(() => import('@provider/reddit'), 'RedditPipeline'),
	[Provider.SexVid]: () => loadPipeline(() => import('@provider/sexvid'), 'SexVidPipeline'),
	[Provider.Shameless]: () => loadPipeline(() => import('@provider/shameless'), 'ShamelessPipeline'),
	[Provider.SuperPorn]: () => loadPipeline(() => import('@provider/superporn'), 'SuperPornPipeline'),
	[Provider.SxyPorn]: () => loadPipeline(() => import('@provider/sxyporn'), 'SxyPornPipeline'),
	[Provider.TheyAreHuge]: () => loadPipeline(() => import('@provider/theyarehuge'), 'TheyAreHugePipeline'),
	[Provider.TikTok]: async () => BasePipeline,
	[Provider.TnAFlix]: () => loadPipeline(() => import('@provider/tnaflix'), 'TnAFlixPipeline'),
	[Provider.TubeVSex]: () => loadPipeline(() => import('@provider/tubevsex'), 'TubeVSexPipeline'),
	[Provider.Tumblr]: () => loadPipeline(() => import('@provider/tumblr'), 'TumblrPipeline'),
	[Provider.Twitter]: () => loadPipeline(() => import('@provider/twitter'), 'TwitterPipeline'),
	[Provider.Unsplash]: () => loadPipeline(() => import('@provider/unsplash'), 'UnsplashPipeline'),
	[Provider.WallHaven]: () => loadPipeline(() => import('@provider/wallhaven'), 'WallHavenPipeline'),
	[Provider.WikiArt]: () => loadPipeline(() => import('@provider/wikiart'), 'WikiArtPipeline'),
	[Provider.Wikimedia]: () => loadPipeline(() => import('@provider/wikimedia'), 'WikimediaPipeline'),
	[Provider.XCafe]: () => loadPipeline(() => import('@provider/xcafe'), 'XCafePipeline'),
	[Provider.XDegu]: () => loadPipeline(() => import('@provider/xdegu'), 'XDeguPipeline'),
	[Provider.XGroovy]: () => loadPipeline(() => import('@provider/xgroovy'), 'XGroovyPipeline'),
	[Provider.XHamster]: () => loadPipeline(() => import('@provider/xhamster'), 'XHamsterPipeline'),
	[Provider.XnXX]: () => loadPipeline(() => import('@provider/xnxx'), 'XnXXPipeline'),
	[Provider.Xozilla]: () => loadPipeline(() => import('@provider/xozilla'), 'XozillaPipeline'),
	[Provider.XVideos]: () => loadPipeline(() => import('@provider/xvideos'), 'XVideosPipeline'),
	[Provider.ZbPorn]: () => loadPipeline(() => import('@provider/zbporn'), 'ZbPornPipeline'),
	[Provider.ZzzTube]: () => loadPipeline(() => import('@provider/zzztube'), 'ZzzTubePipeline')
	// </auto-generated:entries>
};

/**
 * Resolves provider pipelines and builds download work items.
 *
 * @remarks
 * The pipeline registry separates provider lookup from coordinator logic. It
 * lazy-loads the provider pipeline, injects storage support, and returns the
 * concrete items that the download coordinator can process.
 */
export class PipelineRegistry {
	private static readonly cache = new Map<Provider, PipelineCtor>();

	constructor(protected readonly fileManager: FileManager) {}

	private async resolvePipeline(provider: Provider): Promise<PipelineCtor> {
		const cached = PipelineRegistry.cache.get(provider);

		if (cached) return cached;

		/**
		 * The factory table is a `Record<Provider, ...>`, so an unknown provider can
		 * only arrive from an unchecked cast. Failing loudly beats resolving to the
		 * default pipeline and silently extracting the wrong shape.
		 */
		const factory = pipelineFactories[provider];

		if (!factory) throw new Error(`No pipeline registered for provider "${provider}"`);

		const PipelineClass = await factory();

		PipelineRegistry.cache.set(provider, PipelineClass);

		return PipelineClass;
	}

	/**
	 * Builds pipeline items with the matching provider pipeline.
	 *
	 * @param metadata Extracted provider metadata.
	 * @param request Execution request containing the provider.
	 * @returns Downloadable pipeline items.
	 */
	public async build<TResult, TExec extends ExecutionArgs>(metadata: TResult, request: TExec): Promise<PipelineItem[]> {
		const provider = request.provider ?? Provider.Default;

		const PipelineClass = await this.resolvePipeline(provider);

		const pipeline = new PipelineClass(this.fileManager);

		return pipeline.build(metadata, request);
	}
}
