import { BaseTransformer } from '@base';
import { type ExecutionArgs } from '@contracts';
import { type ProgressManager } from '@core/progress';
import { type HttpClient } from '@engine/http';
import { Provider } from '@types';

type TransformerCtor = new (html: HttpClient, progress: ProgressManager) => BaseTransformer<any, any>;

type TransformerFactory = () => Promise<TransformerCtor>;

async function loadTransformer<T>(loader: () => Promise<Record<string, unknown>>, key: string): Promise<T> {
	const mod = await loader();

	const exported = mod[key];

	if (!exported) throw new Error(`Transformer export "${key}" was not found`);

	return exported as T;
}

const transformerFactories: Record<Provider, TransformerFactory> = {
	// <auto-generated:entries>
	[Provider.AnalRz]: () => loadTransformer(() => import('@provider/analrz'), 'AnalRzTransformer'),
	[Provider.ArtStation]: () => loadTransformer(() => import('@provider/artstation'), 'ArtStationTransformer'),
	[Provider.Beeg]: () => loadTransformer(() => import('@provider/beeg'), 'BeegTransformer'),
	[Provider.Behance]: () => loadTransformer(() => import('@provider/behance'), 'BehanceTransformer'),
	[Provider.BlackPorn]: () => loadTransformer(() => import('@provider/blackporn'), 'BlackPornTransformer'),
	[Provider.Bluesky]: () => loadTransformer(() => import('@provider/bluesky'), 'BlueskyTransformer'),
	[Provider.BoKepPorn]: () => loadTransformer(() => import('@provider/bokepporn'), 'BoKepPornTransformer'),
	[Provider.ColliderPorn]: () => loadTransformer(() => import('@provider/colliderporn'), 'ColliderPornTransformer'),
	[Provider.CumLouder]: () => loadTransformer(() => import('@provider/cumlouder'), 'CumLouderTransformer'),
	[Provider.DaFreePorn]: () => loadTransformer(() => import('@provider/dafreeporn'), 'DaFreePornTransformer'),
	[Provider.Danbooru]: () => loadTransformer(() => import('@provider/danbooru'), 'DanbooruTransformer'),
	[Provider.DaNude]: () => loadTransformer(() => import('@provider/danude'), 'DaNudeTransformer'),
	[Provider.Default]: async () => BaseTransformer,
	[Provider.DeviantArt]: () => loadTransformer(() => import('@provider/deviantart'), 'DeviantArtTransformer'),
	[Provider.EpicGfs]: () => loadTransformer(() => import('@provider/epicgfs'), 'EpicGfsTransformer'),
	[Provider.EPorner]: () => loadTransformer(() => import('@provider/eporner'), 'EPornerTransformer'),
	[Provider.Flickr]: () => loadTransformer(() => import('@provider/flickr'), 'FlickrTransformer'),
	[Provider.Gelbooru]: () => loadTransformer(() => import('@provider/gelbooru'), 'GelbooruTransformer'),
	[Provider.HqPorn]: () => loadTransformer(() => import('@provider/hqporn'), 'HqPornTransformer'),
	[Provider.Imgur]: () => loadTransformer(() => import('@provider/imgur'), 'ImgurTransformer'),
	[Provider.Instagram]: () => loadTransformer(() => import('@provider/instagram'), 'InstagramTransformer'),
	[Provider.Interracial]: () => loadTransformer(() => import('@provider/interracial'), 'InterracialTransformer'),
	[Provider.ItsPorn]: () => loadTransformer(() => import('@provider/itsporn'), 'ItsPornTransformer'),
	[Provider.Lesbian8]: () => loadTransformer(() => import('@provider/lesbian8'), 'Lesbian8Transformer'),
	[Provider.MangaDex]: () => loadTransformer(() => import('@provider/mangadex'), 'MangaDexTransformer'),
	[Provider.Mastodon]: () => loadTransformer(() => import('@provider/mastodon'), 'MastodonTransformer'),
	[Provider.MegaTube]: () => loadTransformer(() => import('@provider/megatube'), 'MegaTubeTransformer'),
	[Provider.MomVids]: () => loadTransformer(() => import('@provider/momvids'), 'MomVidsTransformer'),
	[Provider.MyLust]: () => loadTransformer(() => import('@provider/mylust'), 'MyLustTransformer'),
	[Provider.Newgrounds]: () => loadTransformer(() => import('@provider/newgrounds'), 'NewgroundsTransformer'),
	[Provider.OkPorn]: () => loadTransformer(() => import('@provider/okporn'), 'OkPornTransformer'),
	[Provider.PerfectGirls]: () => loadTransformer(() => import('@provider/perfectgirls'), 'PerfectGirlsTransformer'),
	[Provider.Pexels]: () => loadTransformer(() => import('@provider/pexels'), 'PexelsTransformer'),
	[Provider.Pinterest]: () => loadTransformer(() => import('@provider/pinterest'), 'PinterestTransformer'),
	[Provider.Pixiv]: () => loadTransformer(() => import('@provider/pixiv'), 'PixivTransformer'),
	[Provider.Porn300]: () => loadTransformer(() => import('@provider/porn300'), 'Porn300Transformer'),
	[Provider.PornDoe]: () => loadTransformer(() => import('@provider/porndoe'), 'PornDoeTransformer'),
	[Provider.PornHub]: () => loadTransformer(() => import('@provider/pornhub'), 'PornHubTransformer'),
	[Provider.PornId]: () => loadTransformer(() => import('@provider/pornid'), 'PornIdTransformer'),
	[Provider.PornOne]: () => loadTransformer(() => import('@provider/pornone'), 'PornOneTransformer'),
	[Provider.PornSeven]: () => loadTransformer(() => import('@provider/pornseven'), 'PornSevenTransformer'),
	[Provider.PornsOk]: () => loadTransformer(() => import('@provider/pornsok'), 'PornsOkTransformer'),
	[Provider.PussySpace]: () => loadTransformer(() => import('@provider/pussyspace'), 'PussySpaceTransformer'),
	[Provider.Reddit]: () => loadTransformer(() => import('@provider/reddit'), 'RedditTransformer'),
	[Provider.SexVid]: () => loadTransformer(() => import('@provider/sexvid'), 'SexVidTransformer'),
	[Provider.Shameless]: () => loadTransformer(() => import('@provider/shameless'), 'ShamelessTransformer'),
	[Provider.SuperPorn]: () => loadTransformer(() => import('@provider/superporn'), 'SuperPornTransformer'),
	[Provider.SxyPorn]: () => loadTransformer(() => import('@provider/sxyporn'), 'SxyPornTransformer'),
	[Provider.TheyAreHuge]: () => loadTransformer(() => import('@provider/theyarehuge'), 'TheyAreHugeTransformer'),
	[Provider.TikTok]: () => loadTransformer(() => import('@provider/tiktok'), 'TikTokTransformer'),
	[Provider.TnAFlix]: () => loadTransformer(() => import('@provider/tnaflix'), 'TnAFlixTransformer'),
	[Provider.TubeVSex]: () => loadTransformer(() => import('@provider/tubevsex'), 'TubeVSexTransformer'),
	[Provider.Tumblr]: () => loadTransformer(() => import('@provider/tumblr'), 'TumblrTransformer'),
	[Provider.Twitter]: () => loadTransformer(() => import('@provider/twitter'), 'TwitterTransformer'),
	[Provider.Unsplash]: () => loadTransformer(() => import('@provider/unsplash'), 'UnsplashTransformer'),
	[Provider.WallHaven]: () => loadTransformer(() => import('@provider/wallhaven'), 'WallHavenTransformer'),
	[Provider.WikiArt]: () => loadTransformer(() => import('@provider/wikiart'), 'WikiArtTransformer'),
	[Provider.Wikimedia]: () => loadTransformer(() => import('@provider/wikimedia'), 'WikimediaTransformer'),
	[Provider.XCafe]: () => loadTransformer(() => import('@provider/xcafe'), 'XCafeTransformer'),
	[Provider.XDegu]: () => loadTransformer(() => import('@provider/xdegu'), 'XDeguTransformer'),
	[Provider.XGroovy]: () => loadTransformer(() => import('@provider/xgroovy'), 'XGroovyTransformer'),
	[Provider.XHamster]: () => loadTransformer(() => import('@provider/xhamster'), 'XHamsterTransformer'),
	[Provider.XnXX]: () => loadTransformer(() => import('@provider/xnxx'), 'XnXXTransformer'),
	[Provider.Xozilla]: () => loadTransformer(() => import('@provider/xozilla'), 'XozillaTransformer'),
	[Provider.XVideos]: () => loadTransformer(() => import('@provider/xvideos'), 'XVideosTransformer'),
	[Provider.ZbPorn]: () => loadTransformer(() => import('@provider/zbporn'), 'ZbPornTransformer'),
	[Provider.ZzzTube]: () => loadTransformer(() => import('@provider/zzztube'), 'ZzzTubeTransformer')
	// </auto-generated:entries>
};

/**
 * Resolves provider transformers and runs metadata extraction.
 *
 * @remarks
 * The transformer registry lets coordinators ask for "the transformer for this
 * provider" without importing provider modules directly. This keeps startup
 * lighter and preserves a single place for provider-to-class mapping.
 */
export class TransformerRegistry {
	private static readonly cache = new Map<Provider, TransformerCtor>();

	constructor(
		private readonly httpClient: HttpClient,
		private readonly progressManager: ProgressManager
	) {}

	private async resolveTransformer(provider: Provider): Promise<TransformerCtor> {
		const cached = TransformerRegistry.cache.get(provider);

		if (cached) return cached;

		/**
		 * The factory table is a `Record<Provider, ...>`, so an unknown provider can
		 * only arrive from an unchecked cast. Failing loudly beats resolving to the
		 * default transformer and silently extracting the wrong shape.
		 */
		const factory = transformerFactories[provider];

		if (!factory) throw new Error(`No transformer registered for provider "${provider}"`);

		const TransformerClass = await factory();

		TransformerRegistry.cache.set(provider, TransformerClass);

		return TransformerClass;
	}

	/**
	 * Runs the matching transformer for a URL and request.
	 *
	 * @param url Target URL to transform.
	 * @param request Execution request containing the provider.
	 * @returns Provider metadata in the requested result shape.
	 */
	public async transform<TArgs extends ExecutionArgs, TResult>(url: string, request: TArgs): Promise<TResult> {
		const provider = request.provider ?? Provider.Default;

		const TransformerClass = await this.resolveTransformer(provider);

		const transformer = new TransformerClass(this.httpClient, this.progressManager);

		return (await transformer.transform(url, request)) as TResult;
	}
}
