import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { type RegistryCoordinator } from '../../packages/contracts';

interface Registry {
	services: RegistryCoordinator[];
}

const root = process.cwd();
const registryPath = join(root, 'scripts/codegen/registry.json');
const templatesDir = join(root, 'scripts/codegen/templates');

const registry = JSON.parse(readFileSync(registryPath, 'utf-8')) as Registry;

const ensureDir = (filePath: string) => mkdirSync(dirname(filePath), { recursive: true });

const write = (rel: string, content: string) => {
	const p = join(root, rel);
	ensureDir(p);
	writeFileSync(p, content);
	console.log('Wrote', rel);
};

const read = (rel: string) => readFileSync(join(root, rel), 'utf-8');

const loadTemplate = (name: string): string => {
	const p = join(templatesDir, name);
	return readFileSync(p, 'utf-8');
};

const render = (template: string, ctx: Record<string, string>): string => {
	return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, key) => ctx[key] ?? '');
};

function patchRegion(
	source: string,
	region: string,
	content: string,
	startMarker = `// <auto-generated:${region}>`,
	endMarker = `// </auto-generated:${region}>`
): string {
	const regex = new RegExp(
		`${startMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${endMarker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`,
		'g'
	);
	return source.replace(regex, `${startMarker}\n${content}\n\t${endMarker}`);
}

// Create per-service files from templates
for (const svc of registry.services) {
	const name = svc.name;
	const nameLower = name.toLowerCase();
	const execArgsName = `${name}ExecArgs`;
	const outputName = `${name}Output`;
	const methodName = `${name}Methods`;

	const execPath = `packages/providers/${nameLower}/${name}Contracts.ts`;
	if (!existsSync(join(root, execPath))) {
		write(execPath, render(loadTemplate('ProviderExecArgs.hbs'), { ArgsName: execArgsName }));
	}

	const fileContent = readFileSync(join(root, execPath), 'utf-8');
	if (!fileContent.includes(outputName)) {
		writeFileSync(join(root, execPath), fileContent + '\n' + render(loadTemplate('ProviderOutput.hbs'), { OutputName: outputName }));
	}

	if (svc.method) {
		const methodPath = `packages/providers/${nameLower}/${name}Types.ts`;
		if (!existsSync(join(root, methodPath))) {
			write(methodPath, render(loadTemplate('ProviderMethods.hbs'), { MethodName: methodName }));
		}
	}

	if (svc.parser) {
		const parserPath = `packages/providers/${nameLower}/${name}Parser.ts`;
		if (!existsSync(join(root, parserPath))) {
			write(parserPath, render(loadTemplate('parser.hbs'), { ProviderName: name }));
		}
	}

	const providerPath = `packages/providers/${nameLower}/${name}Provider.ts`;
	if (!existsSync(join(root, providerPath))) {
		write(providerPath, render(loadTemplate('provider.hbs'), { ProviderName: name, ArgsName: execArgsName }));
	}

	if (svc.pipeline) {
		const pipelinePath = `packages/providers/${nameLower}/${name}Pipeline.ts`;
		if (!existsSync(join(root, pipelinePath))) {
			write(
				pipelinePath,
				render(loadTemplate('pipeline.hbs'), { ProviderName: name, ArgsName: execArgsName, OutputName: outputName })
			);
		}
	}

	if (svc.transformer) {
		const transformerPath = `packages/providers/${nameLower}/${name}Transformer.ts`;
		if (!existsSync(join(root, transformerPath))) {
			write(
				transformerPath,
				render(loadTemplate('transformer.hbs'), {
					ProviderName: name,
					ArgsName: execArgsName,
					OutputName: outputName,
					MethodName: methodName
				})
			);
		}
	}

	if (svc.strategy) {
		const strategyPath = `packages/providers/${nameLower}/${name}Strategy.ts`;
		if (!existsSync(join(root, strategyPath))) {
			write(strategyPath, render(loadTemplate('strategy.hbs'), { ProviderName: name }));
		}
	}
}

const execTypesPath = 'packages/types/ExecutionTypes.ts';
let execTypes = read(execTypesPath);
const members = registry.services
	.map((s) => `\t${s.name} = '${s.name}Provider',`)
	.sort((a, b) => a.localeCompare(b))
	.join('\n');
execTypes = patchRegion(execTypes, 'entries', members);
write(execTypesPath, execTypes);

// tsconfig.json
const tsConfigPath = 'tsconfig.json';
let tsConfigReg = read(tsConfigPath);
const tsEntries = registry.services
	.map((s) => {
		const toLowerCase = s.name.toLowerCase();
		return `\t\t\t"@provider/${toLowerCase}": ["./packages/providers/${toLowerCase}/index.ts"]`;
	})
	.sort((a, b) => a.localeCompare(b))
	.join(',\n\n');
tsConfigReg = patchRegion(tsConfigReg, 'entries', tsEntries);
write(tsConfigPath, tsConfigReg);

console.log('\n\nCodegen finished. Next steps:');
console.log('- If your editor shows ESLint/TS errors, reload the window.');
console.log("- Run 'pnpm run make:index' then 'pnpm run format' to update barrels and format.");
